/* The whole SDK in one include. */
#ifndef OOPS_H
#define OOPS_H

#include "oops/agc.h"
#include "oops/audio.h"
#include "oops/audiodec.h"
#include "oops/dialog.h"
#include "oops/display.h"
#include "oops/draw.h"
#include "oops/escalate.h"
#include "oops/freestd.h"
#include "oops/fs.h"
#include "oops/gpu.h"
#include "oops/heap.h"
#include "oops/inject.h"
#include "oops/input.h"
#include "oops/jit.h"
#include "oops/keyboard.h"
#include "oops/krw.h"
#include "oops/math.h"
#include "oops/memory.h"
#include "oops/mouse.h"
#include "oops/net.h"
#include "oops/netctl.h"
#include "oops/offsets.h"
#include "oops/pkg.h"
#include "oops/savedata.h"
#include "oops/syscall.h"
#include "oops/sysmodule.h"
#include "oops/system.h"
#include "oops/target.h"
#include "oops/thread.h"
#include "oops/time.h"
#include "oops/videodec.h"

#endif /* OOPS_H */
