#!/usr/bin/env bash
# Regenerate docs/API_INDEX.md: every public entry point this SDK offers, by header.
#
# It exists because the SDK is 34 headers wide and a session that cannot see that in one
# place writes a second one. Four times over 2026-09-23/24 a facility was reinvented that
# already existed - log levels beside oops_log_set_level, a savedata path beside
# oops_savedata_mount, a writable directory beside /app0. Each cost a hardware run or more.
#
# Grep is not the answer on its own: it finds a name you already guessed. This lists what is
# there so a concept can be recognised without knowing its name in advance.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SDK="$(cd "$HERE/.." && pwd)"
OUT="$SDK/docs/API_INDEX.md"

{
  echo "# oops-sdk public API index"
  echo
  echo "Generated by \`tools/api-index.sh\`. **Read this before adding an entry point.**"
  echo "If what you are about to write is already here under another name, use that one."
  echo
  echo "For declarative subsystem capabilities used in application Makefiles, see [**docs/FEATURES.md**](FEATURES.md)."
  echo
  # **Tracked headers only.** The index is committed, so generating it from whatever is on disk
  # publishes any header another session has in flight and has not committed - their API surface
  # appears in this repository's documentation before they have decided it is the API. Asking git
  # rather than the filesystem also makes the output the same for everyone: two people with
  # different uncommitted work regenerate the same file rather than reverting each other.
  for h in $(cd "$SDK/include" && git ls-files '*.h' | sort); do
    decls=$(grep -hoE '^[a-zA-Z_][a-zA-Z0-9_ *]*\b(oops_[a-z0-9_]+|gl[A-Z][A-Za-z0-9]*)\s*\(' \
              "$SDK/include/$h" 2>/dev/null \
            | grep -oE '(oops_[a-z0-9_]+|gl[A-Z][A-Za-z0-9]*)' | sort -u || true)
    [ -z "$decls" ] && continue
    echo "## $h"
    echo
    echo "$decls" | sed 's/^/- `/; s/$/`/'
    echo
  done
} > "$OUT"

echo "wrote $OUT ($(grep -c '^- ' "$OUT") entry points across $(grep -c '^## ' "$OUT") headers)"
