#!/usr/bin/env bash
# Generates docs/API_INDEX.md: every public entry point this SDK offers, by header.
#
#   tools/api-index.sh           write docs/API_INDEX.md
#   tools/api-index.sh --check   fail when the committed index differs from a fresh generation
#
# The index lists what exists so a concept can be recognised without knowing its name. It
# reads committed headers at their committed contents (`git show HEAD:`), so uncommitted work
# never reaches the published index and every checkout generates the same file.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SDK="$(cd "$HERE/.." && pwd)"
OUT="$SDK/docs/API_INDEX.md"

generate() {
    echo "# oops-sdk public API index"
    echo
    echo "Generated by \`tools/api-index.sh\`. Read this before adding an entry point."
    echo "If what you are about to write is already here under another name, use that one."
    echo
    echo "For declarative subsystem capabilities used in application Makefiles, see [docs/FEATURES.md](FEATURES.md)."
    echo
    for h in $(cd "$SDK/include" && git ls-files '*.h' | sort); do
        decls=$(git -C "$SDK" show "HEAD:include/$h" 2>/dev/null |
            grep -hoE '^[a-zA-Z_][a-zA-Z0-9_ *]*\b(oops_[a-z0-9_]+|gl[A-Z][A-Za-z0-9]*)\s*\(' |
            grep -oE '(oops_[a-z0-9_]+|gl[A-Z][A-Za-z0-9]*)' | sort -u || true)
        [ -z "$decls" ] && continue
        echo "## $h"
        echo
        echo "$decls" | sed 's/^/- `/; s/$/`/'
        echo
    done
}

if [ "${1:-}" = "--check" ]; then
    if ! diff -u "$OUT" <(generate) >&2; then
        echo "oops-sdk: docs/API_INDEX.md is out of date; run tools/api-index.sh" >&2
        exit 1
    fi
    echo "oops-sdk: API index up to date"
    exit 0
fi

generate >"$OUT"
echo "wrote $OUT ($(grep -c '^- ' "$OUT") entry points across $(grep -c '^## ' "$OUT") headers)"
